package com.d3h1.takemycall.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF6200EE)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFBB86FC)
val LightOnPrimaryContainer = Color(0xFF3700B3)
val LightSecondary = Color(0xFF03DAC6)
val LightOnSecondary = Color(0xFF000000)
val LightSecondaryContainer = Color(0xFF018786)
val LightOnSecondaryContainer = Color(0xFFFFFFFF)
val LightTertiary = Color(0xFF018786)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFBB86FC)
val LightOnTertiaryContainer = Color(0xFF3700B3)
val LightBackground = Color(0xFFF1F1F1)
val LightOnBackground = Color(0xFF000000)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF000000)
val LightSurfaceVariant = Color(0xFFEEEEEE)
val LightOnSurfaceVariant = Color(0xFF000000)
val LightError = Color(0xFFB00020)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD4)
val LightOnErrorContainer = Color(0xFF410E0B)
val LightOutline = Color(0xFF737373)
val LightInverseSurface = Color(0xFF121212)
val LightInverseOnSurface = Color(0xFFFFFFFF)
val LightInversePrimary = Color(0xFFBB86FC)

val DarkPrimary = Color(0xFFBB86FC)
val DarkOnPrimary = Color(0xFF3700B3)
val DarkPrimaryContainer = Color(0xFF3700B3)
val DarkOnPrimaryContainer = Color(0xFFBB86FC)
val DarkSecondary = Color(0xFF03DAC6)
val DarkOnSecondary = Color(0xFF000000)
val DarkSecondaryContainer = Color(0xFF018786)
val DarkOnSecondaryContainer = Color(0xFFBB86FC)
val DarkTertiary = Color(0xFF03DAC6)
val DarkOnTertiary = Color(0xFF000000)
val DarkTertiaryContainer = Color(0xFFBB86FC)
val DarkOnTertiaryContainer = Color(0xFF3700B3)
val DarkBackground = Color(0xFF121212)
val DarkOnBackground = Color(0xFFFFFFFF)
val DarkSurface = Color(0xFF1E1E1E)
val DarkOnSurface = Color(0xFFFFFFFF)
val DarkSurfaceVariant = Color(0xFF2C2C2C)
val DarkOnSurfaceVariant = Color(0xFFEEEEEE)
val DarkError = Color(0xFFCF6679)
val DarkOnError = Color(0xFF410E0B)
val DarkErrorContainer = Color(0xFF3700B3)
val DarkOnErrorContainer = Color(0xFFBB86FC)
val DarkOutline = Color(0xFFBDBDBD)
val DarkInverseSurface = Color(0xFFFFFFFF)
val DarkInverseOnSurface = Color(0xFF121212)
val DarkInversePrimary = Color(0xFF6200EE)